import {TransactionType} from 'nem2-sdk'

import {
  FormattedTransfer,
  FormattedRegisterNamespace,
  FormattedAddressAlias,
  FormattedMosaicAlias,
  FormattedMosaicDefinition,
  FormattedMosaicSupplyChange,
  FormattedModifyMultisigAccount,
  FormattedAggregateComplete,
  FormattedAggregateBonded,
  FormattedLock,
  FormattedSecretLock,
  FormattedSecretProof,
  FormattedAccountRestrictionAddress,
  FormattedAccountRestrictionMosaic,
  FormattedAccountRestrictionOperation,
  FormattedLinkAccount,
  FormattedMosaicAddressRestriction,
  FormattedMosaicGlobalRestriction,
  FormattedAccountMetadataTransaction,
  FormattedMosaicMetadataTransaction,
  FormattedNamespaceMetadataTransaction,
} from '@/core/model'

export const transactionTypeToFormattedTransaction = (type: string) => ({
  [TransactionType.TRANSFER]: FormattedTransfer,
  [TransactionType.NAMESPACE_REGISTRATION]: FormattedRegisterNamespace,
  [TransactionType.ADDRESS_ALIAS]: FormattedAddressAlias,
  [TransactionType.MOSAIC_ALIAS]: FormattedMosaicAlias,
  [TransactionType.MOSAIC_DEFINITION]: FormattedMosaicDefinition,
  [TransactionType.MOSAIC_SUPPLY_CHANGE]: FormattedMosaicSupplyChange,
  [TransactionType.MULTISIG_ACCOUNT_MODIFICATION]: FormattedModifyMultisigAccount,
  [TransactionType.AGGREGATE_COMPLETE]: FormattedAggregateComplete,
  [TransactionType.AGGREGATE_BONDED]: FormattedAggregateBonded,
  [TransactionType.HASH_LOCK]: FormattedLock,
  [TransactionType.SECRET_LOCK]: FormattedSecretLock,
  [TransactionType.SECRET_PROOF]: FormattedSecretProof,
  [TransactionType.ACCOUNT_ADDRESS_RESTRICTION]: FormattedAccountRestrictionAddress,
  [TransactionType.ACCOUNT_MOSAIC_RESTRICTION]: FormattedAccountRestrictionMosaic,
  [TransactionType.ACCOUNT_OPERATION_RESTRICTION]: FormattedAccountRestrictionOperation,
  [TransactionType.ACCOUNT_LINK]: FormattedLinkAccount,
  [TransactionType.MOSAIC_ADDRESS_RESTRICTION]: FormattedMosaicAddressRestriction,
  [TransactionType.MOSAIC_GLOBAL_RESTRICTION]: FormattedMosaicGlobalRestriction,
  [TransactionType.ACCOUNT_METADATA]: FormattedAccountMetadataTransaction,
  [TransactionType.MOSAIC_METADATA]: FormattedMosaicMetadataTransaction,
  [TransactionType.NAMESPACE_METADATA]: FormattedNamespaceMetadataTransaction,
}[type])
